MIST_BUILD_TYPE ?= UNOFFICIAL

# MIST Props
MIST_BASE_VERSION = 1.1
MIST_CODENAME := Alpha

MIST_DATE_YEAR := $(shell date -u +%Y)
MIST_DATE_MONTH := $(shell date -u +%m)
MIST_DATE_DAY := $(shell date -u +%d)
MIST_DATE_HOUR := $(shell date -u +%H)
MIST_DATE_MINUTE := $(shell date -u +%M)
MIST_BUILD_DATE_UTC := $(shell date -d '$(MIST_DATE_YEAR)-$(MIST_DATE_MONTH)-$(MIST_DATE_DAY) $(MIST_DATE_HOUR):$(MIST_DATE_MINUTE) UTC' +%s)
MIST_BUILD_DATE := $(MIST_DATE_YEAR)$(MIST_DATE_MONTH)$(MIST_DATE_DAY)-$(MIST_DATE_HOUR)$(MIST_DATE_MINUTE)

MIST_PLATFORM_VERSION := 13

MIST_VERSION := MistOS_$(MIST_BASE_VERSION)_$(MIST_BUILD)-$(MIST_PLATFORM_VERSION)-$(MIST_BUILD_DATE)-$(MIST_BUILD_TYPE)
MIST_VERSION_PROP := fourteen
