MIST_PLATFORM_VERSION = 14

MIST_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

MIST_BUILDTYPE ?= UNOFFICIAL

MIST_VERSION_SUFFIX := $(MIST_BUILD_DATE)-$(MIST_BUILDTYPE)$(MIST_EXTRAVERSION)

# Internal version
MIST_VERSION := $(MIST_PLATFORM_VERSION)-$(MIST_VERSION_SUFFIX)-$(MIST_BUILD)

# Display version
MIST_DISPLAY_VERSION := $(MIST_PLATFORM_VERSION)-$(MIST_VERSION_SUFFIX)
